### ISSUE TITLE
Facing issue in ITCRM1 in Account section receiving payment option 

### ISSUE THREAD

**Issue by sajusamuel** [MyITCRM/myitcrm2#20]
Hi,

In Account section , unpaid invoice, clicking on the receiving payment button, it takes to me a white blank screen.

Please let me know what to do.

**Comment by sajusamuel** [comment]
Solved by myself. thanks..

**Comment by topherbones** [comment]
I have been fighting like crazy with the same issue.... just stopped working one day.... What did you do to fix it?

**Comment by topherbones** [comment]
Found the solution: https://github.com/MyITCRM/myitcrm1/blob/d4cda7d1da3e6d1b6ea7826926af5df8dd3e6283/modules/billing/include.php

Copy and paste in over the script in the include.php
